name: Bug
description: An unexpected problem or behavior
type: Bug
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect?
      placeholder: e.g., The app crashes when I click the save button.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: e.g., The app should save the file without crashing.
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: OS
      description: Which operating system?
      multiple: true
    options:
      - Windows
      - macOS
      - Linux
      - Android
      - iOS
      - Web
  - type: input
    id: version
    attributes:
      label: Version
      description: App or library version
      placeholder: e.g., v1.0.0
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the bug here.
      placeholder: e.g., links, logs, references, related issues.
    validations:
      required: false
