name: Feature
description: A request, idea, or new functionality
type: Feature
body:
  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Briefly describe the feature.
      placeholder: e.g., Add support for dark mode.
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Detailed Explanation
      description: Describe the feature in detail.
      placeholder: e.g., When enabled, the UI switches to a dark color scheme.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots.
      placeholder: e.g., links, references, related issues.
    validations:
      required: false
