name: Task
description: A non-technical or low-effort technical task
type: Task
body:
  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: What is the task?
      placeholder: e.g., Migrate package to new version.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or resources.
      placeholder: e.g., links, references, related issues.
    validations:
      required: false
